name: jobapp-frontend-dev

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: jobapp-frontend:dev
    container_name: jobapp-frontend-dev
    ports:
      - "3000:80"
    environment:
      API_URL: "/api"
      API_UPSTREAM: "http://jobapp-backend-dev:8080"
    restart: unless-stopped
    networks:
      - jobapp-net

networks:
  jobapp-net:
    external: true
